### ISSUE TITLE
`--inside-venv` error in installed package

### ISSUE THREAD

**Issue by penguin-wwy** [python/pyperformance#120]
My command:
```
./bin/python3 -m pyperformance run --affinity 1 -o dev.json
```

Output:
```
...
...

Execute: /data/pipeline/pipeline_guard/python-3.6dev-b501-release/venv/cpython3.6-ce4115b70348-compat-338b0f56cea8/bin/python -m pip freeze
packaging==21.3
pyparsing==3.0.6
pyperf==2.3.0
pyperformance==1.0.3
toml==0.10.2

Traceback (most recent call last):
  File "/data/pipeline/pipeline_guard/python-3.6dev-b501-release/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/pipeline/pipeline_guard/python-3.6dev-b501-release/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/pipeline/pipeline_guard/python-3.6dev-b501-release/venv/cpython3.6-ce4115b70348-compat-338b0f56cea8/lib/python3.6/site-packages/pyperformance/__main__.py", line 2, in <module>
    pyperformance.cli.main()
  File "/data/pipeline/pipeline_guard/python-3.6dev-b501-release/venv/cpython3.6-ce4115b70348-compat-338b0f56cea8/lib/python3.6/site-packages/pyperformance/cli.py", line 306, in main
    _main()
  File "/data/pipeline/pipeline_guard/python-3.6dev-b501-release/venv/cpython3.6-ce4115b70348-compat-338b0f56cea8/lib/python3.6/site-packages/pyperformance/cli.py", line 255, in _main
    assert not options.inside_venv
AssertionError
```

Add log and print the subprocess command which executed in `exec_in_virtualenv`.  Then error:
```
[test@TENCENT64 /data/pipeline/pipeline_guard/python-3.6dev-b501-release]$ /data/pipeline/pipeline_guard/python-3.6dev-b501-release/venv/cpython3.6-ce4115b70348-compat-338b0f56cea8/bin/python -m pyperformance run --affinity 1 -o dev.json --inside-venv
Traceback (most recent call last):
  File "/data/pipeline/pipeline_guard/python-3.6dev-b501-release/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/pipeline/pipeline_guard/python-3.6dev-b501-release/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/pipeline/pipeline_guard/python-3.6dev-b501-release/venv/cpython3.6-ce4115b70348-compat-338b0f56cea8/lib/python3.6/site-packages/pyperformance/__main__.py", line 2, in <module>
    pyperformance.cli.main()
  File "/data/pipeline/pipeline_guard/python-3.6dev-b501-release/venv/cpython3.6-ce4115b70348-compat-338b0f56cea8/lib/python3.6/site-packages/pyperformance/cli.py", line 306, in main
    _main()
  File "/data/pipeline/pipeline_guard/python-3.6dev-b501-release/venv/cpython3.6-ce4115b70348-compat-338b0f56cea8/lib/python3.6/site-packages/pyperformance/cli.py", line 255, in _main
    assert not options.inside_venv
AssertionError
```

https://github.com/python/pyperformance/blob/11ee8985749f60d2de4a07e35034865b4afe582f/pyperformance/cli.py#L251-L258

https://github.com/python/pyperformance/blob/11ee8985749f60d2de4a07e35034865b4afe582f/pyperformance/__init__.py#L12-L14

`is_installed` means **setup.py** is existed ? If this is the case then I cannot use `--inside-venv` after `pip install`.

How do I use it properly, or is this a problem that needs to be fixed?

Thank you :)

**Comment by corydolphin** [comment]
I hit the same issue. Downgrading to 1.0.1 works, suggesting it is in the last two versions

**Comment by gpshead** [comment]
https://github.com/python/pyperformance/pull/109 caused this regression in 1.0.3. `pip install pyperformance==1.0.2` appears to work. @ericsnowcurrently

**Comment by gpshead** [comment]
In my case I hit this when effectively trying to do:

```
build% ../cpython/configure --prefix=/some/place && make install
/some/place/bin/pip install pyperformance
/some/place/bin/pyperformance run
```

**Comment by pablogsal** [comment]
I'm going to yank in PyPI the 1.0.3 release as it seems is broken :(

**Comment by ericsnowcurrently** [comment]
I'm looking into this.

**Comment by ericsnowcurrently** [comment]
@gpshead, @penguin-wwy, @corydolphin, I've pushed what should be a fix.  Would you mind checking the latest `main` branch to verify the problem is gone?  Thanks!

**Comment by gpshead** [comment]
It appears to work now.

build a python with --prefix and installed it, used install/bin/python -m pip install . in a pyperformance checkout, and used install/bin/pyperformance to run a benchmark.  success.

thanks!

**Comment by ericsnowcurrently** [comment]
Thanks, @gpshead!

@pablogsal, we should be good to do another release.  Sorry about that.
