### ISSUE TITLE
Commands fail if --manifest is a relative path.

### ISSUE THREAD

**Issue by ericsnowcurrently** [python/pyperformance#125]
```
$ # python3 -m pyperformance list --manifest pyperformance/data-files/benchmarks/MANIFEST
$ python3 -m pyperformance list --manifest ./pyperformance/data-files/benchmarks/MANIFEST
switching to a venv.
...

Traceback (most recent call last):
  File "<py-install>/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "<py-install>/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "<pyperformance-root>/pyperformance/__main__.py", line 2, in <module>
    pyperformance.cli.main()
  File "<pyperformance-root>/pyperformance/cli.py", line 308, in main
    _main()
  File "<pyperformance-root>/pyperformance/cli.py", line 294, in _main
    benchmarks = _benchmarks_from_options(options)
  File "<pyperformance-root>/pyperformance/cli.py", line 224, in _benchmarks_from_options
    manifest = _manifest_from_options(options)
  File "<pyperformance-root>/pyperformance/cli.py", line 218, in _manifest_from_options
    return _manifest.load_manifest(options.manifest)
  File "<pyperformance-root>/pyperformance/_manifest.py", line 28, in load_manifest
    return BenchmarksManifest._from_sections(sections, resolve, filename)
  File "<pyperformance-root>/pyperformance/_manifest.py", line 69, in _from_sections
    self._add_sections(sections, resolve)
  File "<pyperformance-root>/pyperformance/_manifest.py", line 113, in _add_sections
    for filename, section, data in sections:
  File "<pyperformance-root>/pyperformance/_manifest.py", line 279, in _parse_manifest_file
    filename = _utils.resolve_file(filename, relroot)
  File "<pyperformance-root>/pyperformance/_utils.py", line 64, in resolve_file
    raise NotImplementedError(relroot)
NotImplementedError: ./pyperformance/data-files/benchmarks
```

**Comment by pablogsal** [comment]
Do you want me to hold the release until this is fixed?

**Comment by ericsnowcurrently** [comment]
Don't wait.  It's only a minor annoyance and I'm not sure what would have to change.  So waiting won't benefit much.
