### ISSUE TITLE
`--python` argument breaks package dependencies

### ISSUE THREAD

**Issue by kmod** [python/pyperformance#143]
It looks like if you pass the `--python` argument, `pyperformance run` does the following things:
- Creates a virtual environment using that argument and installs the dependencies
- Runs the benchmark using the argument -- not the new virtual environment!

So as a result any benchmark that has any dependencies will fail unless those dependencies are installed in the original environment (and it will use whatever versions of them it finds there).

I think the fix is to only use the --python argument for creating the venv, and then use the venv python for running the benchmarks.

Here's a log showing what I mean:
```
$ /home/kmod/python-benchmarks/tester/data/build/pyston/build/system_env/bin/pyperformance run --python=/home/kmod/python-benchmarks/tester/data/build/pyston/build/system_env/bin/python3 -b crypto_pyaes
Python benchmark suite 1.0.4

( 1/1) creating venv for benchmark (crypto_pyaes)
Creating the virtual environment /home/kmod/python-benchmarks/tester/venv/cpython3.8-5ac50705c503-compat-f6a835d45d46-bm-crypto_pyaes
Execute: /usr/bin/python3.8 -m venv --without-pip /home/kmod/python-benchmarks/tester/venv/cpython3.8-5ac50705c503-compat-f6a835d45d46-bm-crypto_pyaes
Execute: /home/kmod/python-benchmarks/tester/venv/cpython3.8-5ac50705c503-compat-f6a835d45d46-bm-crypto_pyaes/bin/python -c 'import sys; print(sys.hexversion)'
Python hexversion: 3080af0
Execute: /home/kmod/python-benchmarks/tester/venv/cpython3.8-5ac50705c503-compat-f6a835d45d46-bm-crypto_pyaes/bin/python -m ensurepip --verbose
Non-user install because user site-packages disabled
Ignoring indexes: https://pypi.org/simple
Created temporary directory: /tmp/pip-ephem-wheel-cache-c0lo5nu7
Created temporary directory: /tmp/pip-req-tracker-37c__rl_
Initialized build tracking at /tmp/pip-req-tracker-37c__rl_
Created build tracker: /tmp/pip-req-tracker-37c__rl_
Entered build tracker: /tmp/pip-req-tracker-37c__rl_
Created temporary directory: /tmp/pip-install-x6m_yvhs
Looking in links: /tmp/tmp5ovz4srl
0 location(s) to search for versions of setuptools:
Skipping link: not a file: /tmp/tmp5ovz4srl (from -f)
Skipping link: wrong project name (not setuptools): file:///tmp/tmp5ovz4srl/pkg_resources-0.0.0-py2.py3-none-any.whl
Skipping link: wrong project name (not setuptools): file:///tmp/tmp5ovz4srl/pip-20.0.2-py2.py3-none-any.whl
Found link file:///tmp/tmp5ovz4srl/setuptools-44.0.0-py2.py3-none-any.whl, version: 44.0.0
Local files found: /tmp/tmp5ovz4srl/setuptools-44.0.0-py2.py3-none-any.whl
Given no hashes to check 1 links for project 'setuptools': discarding no candidates
Using version 44.0.0 (newest of versions: 44.0.0)
Processing /tmp/tmp5ovz4srl/setuptools-44.0.0-py2.py3-none-any.whl
  Added setuptools from file:///tmp/tmp5ovz4srl/setuptools-44.0.0-py2.py3-none-any.whl to build tracker '/tmp/pip-req-tracker-37c__rl_'
  Removed setuptools from file:///tmp/tmp5ovz4srl/setuptools-44.0.0-py2.py3-none-any.whl from build tracker '/tmp/pip-req-tracker-37c__rl_'
0 location(s) to search for versions of pip:
Found link file:///tmp/tmp5ovz4srl/pip-20.0.2-py2.py3-none-any.whl, version: 20.0.2
Skipping link: wrong project name (not pip): file:///tmp/tmp5ovz4srl/setuptools-44.0.0-py2.py3-none-any.whl
Local files found: /tmp/tmp5ovz4srl/pip-20.0.2-py2.py3-none-any.whl
Given no hashes to check 1 links for project 'pip': discarding no candidates
Using version 20.0.2 (newest of versions: 20.0.2)
Processing /tmp/tmp5ovz4srl/pip-20.0.2-py2.py3-none-any.whl
  Added pip from file:///tmp/tmp5ovz4srl/pip-20.0.2-py2.py3-none-any.whl to build tracker '/tmp/pip-req-tracker-37c__rl_'
  Removed pip from file:///tmp/tmp5ovz4srl/pip-20.0.2-py2.py3-none-any.whl from build tracker '/tmp/pip-req-tracker-37c__rl_'
0 location(s) to search for versions of pkg-resources:
Found link file:///tmp/tmp5ovz4srl/pkg_resources-0.0.0-py2.py3-none-any.whl, version: 0.0.0
Local files found: /tmp/tmp5ovz4srl/pkg_resources-0.0.0-py2.py3-none-any.whl
Given no hashes to check 1 links for project 'pkg-resources': discarding no candidates
Using version 0.0.0 (newest of versions: 0.0.0)
Processing /tmp/tmp5ovz4srl/pkg_resources-0.0.0-py2.py3-none-any.whl
  Added pkg_resources from file:///tmp/tmp5ovz4srl/pkg_resources-0.0.0-py2.py3-none-any.whl to build tracker '/tmp/pip-req-tracker-37c__rl_'
  Removed pkg_resources from file:///tmp/tmp5ovz4srl/pkg_resources-0.0.0-py2.py3-none-any.whl from build tracker '/tmp/pip-req-tracker-37c__rl_'
Installing collected packages: setuptools, pip, pkg-resources
  Created temporary directory: /tmp/pip-unpacked-wheel-rrmsh9xo

  changing mode of /home/kmod/python-benchmarks/tester/venv/cpython3.8-5ac50705c503-compat-f6a835d45d46-bm-crypto_pyaes/bin/easy_install-3.8 to 775
  Created temporary directory: /tmp/pip-unpacked-wheel-dvy_0pgb

  changing mode of /home/kmod/python-benchmarks/tester/venv/cpython3.8-5ac50705c503-compat-f6a835d45d46-bm-crypto_pyaes/bin/pip3 to 775
  changing mode of /home/kmod/python-benchmarks/tester/venv/cpython3.8-5ac50705c503-compat-f6a835d45d46-bm-crypto_pyaes/bin/pip3.8 to 775
  Created temporary directory: /tmp/pip-unpacked-wheel-zjo19f81

Successfully installed pip-20.0.2 pkg-resources-0.0.0 setuptools-44.0.0
Cleaning up...
Removed build tracker: '/tmp/pip-req-tracker-37c__rl_'
Execute: /home/kmod/python-benchmarks/tester/venv/cpython3.8-5ac50705c503-compat-f6a835d45d46-bm-crypto_pyaes/bin/python -m pip --version
pip 20.0.2 from /home/kmod/python-benchmarks/tester/venv/cpython3.8-5ac50705c503-compat-f6a835d45d46-bm-crypto_pyaes/lib/python3.8/site-packages/pip (python 3.8)
Installing the virtual environment /home/kmod/python-benchmarks/tester/venv/cpython3.8-5ac50705c503-compat-f6a835d45d46-bm-crypto_pyaes
Execute: /home/kmod/python-benchmarks/tester/venv/cpython3.8-5ac50705c503-compat-f6a835d45d46-bm-crypto_pyaes/bin/python -m pip install -U 'pip>=6.0'
Collecting pip>=6.0
  Using cached pip-22.0.3-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Uninstalling pip-20.0.2:
      Successfully uninstalled pip-20.0.2
Successfully installed pip-22.0.3

Execute: /home/kmod/python-benchmarks/tester/venv/cpython3.8-5ac50705c503-compat-f6a835d45d46-bm-crypto_pyaes/bin/python -m pip install -U 'setuptools>=18.5' wheel
Requirement already satisfied: setuptools>=18.5 in ./venv/cpython3.8-5ac50705c503-compat-f6a835d45d46-bm-crypto_pyaes/lib/python3.8/site-packages (44.0.0)
Collecting setuptools>=18.5
  Using cached setuptools-60.9.3-py3-none-any.whl (1.1 MB)
Collecting wheel
  Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel, setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 44.0.0
    Uninstalling setuptools-44.0.0:
      Successfully uninstalled setuptools-44.0.0
Successfully installed setuptools-60.9.3 wheel-0.37.1

Execute: /home/kmod/python-benchmarks/tester/venv/cpython3.8-5ac50705c503-compat-f6a835d45d46-bm-crypto_pyaes/bin/python -m pip install pyperformance==1.0.4
Collecting pyperformance==1.0.4
  Using cached pyperformance-1.0.4-py3-none-any.whl (2.3 MB)
Collecting pyperf
  Using cached pyperf-2.3.1-py2.py3-none-any.whl (88 kB)
Collecting packaging
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting toml
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.7-py3-none-any.whl (98 kB)
Installing collected packages: pyperf, toml, pyparsing, packaging, pyperformance
Successfully installed packaging-21.3 pyparsing-3.0.7 pyperf-2.3.1 pyperformance-1.0.4 toml-0.10.2

Execute: /home/kmod/python-benchmarks/tester/venv/cpython3.8-5ac50705c503-compat-f6a835d45d46-bm-crypto_pyaes/bin/python -m pip --version
pip 22.0.3 from /home/kmod/python-benchmarks/tester/venv/cpython3.8-5ac50705c503-compat-f6a835d45d46-bm-crypto_pyaes/lib/python3.8/site-packages/pip (python 3.8)

Execute: /home/kmod/python-benchmarks/tester/venv/cpython3.8-5ac50705c503-compat-f6a835d45d46-bm-crypto_pyaes/bin/python -m pip freeze
packaging==21.3
pkg_resources==0.0.0
pyparsing==3.0.7
pyperf==2.3.1
pyperformance==1.0.4
toml==0.10.2

Installing requirements into the virtual environment /home/kmod/python-benchmarks/tester/venv/cpython3.8-5ac50705c503-compat-f6a835d45d46-bm-crypto_pyaes
Installing the virtual environment /home/kmod/python-benchmarks/tester/venv/cpython3.8-5ac50705c503-compat-f6a835d45d46-bm-crypto_pyaes
(already installed)
Execute: /home/kmod/python-benchmarks/tester/venv/cpython3.8-5ac50705c503-compat-f6a835d45d46-bm-crypto_pyaes/bin/python -m pip install pyaes==1.6.1 pyperf==2.3.0
Collecting pyaes==1.6.1
  Using cached pyaes-1.6.1-py3-none-any.whl
Collecting pyperf==2.3.0
  Using cached pyperf-2.3.0-py2.py3-none-any.whl (88 kB)
Installing collected packages: pyperf, pyaes
  Attempting uninstall: pyperf
    Found existing installation: pyperf 2.3.1
    Uninstalling pyperf-2.3.1:
      Successfully uninstalled pyperf-2.3.1
Successfully installed pyaes-1.6.1 pyperf-2.3.0
Execute: /home/kmod/python-benchmarks/tester/venv/cpython3.8-5ac50705c503-compat-f6a835d45d46-bm-crypto_pyaes/bin/python -m pip freeze
packaging==21.3
pkg_resources==0.0.0
pyaes==1.6.1
pyparsing==3.0.7
pyperf==2.3.0
pyperformance==1.0.4
toml==0.10.2

[1/1] crypto_pyaes...
INFO:root:Running `/home/kmod/python-benchmarks/tester/data/build/pyston/build/system_env/bin/python3 -u /home/kmod/python-benchmarks/tester/data/build/pyston/build/system_env/lib/python3.8/site-packages/pyperformance/data-files/benchmarks/bm_crypto_pyaes/run_benchmark.py --output /tmp/tmpi2l__ajs --inherit-environ PYPERFORMANCE_RUNID`
Traceback (most recent call last):
  File "/home/kmod/python-benchmarks/tester/data/build/pyston/build/system_env/lib/python3.8/site-packages/pyperformance/data-files/benchmarks/bm_crypto_pyaes/run_benchmark.py", line 10, in <module>
    import pyaes
ModuleNotFoundError: No module named 'pyaes'
ERROR: Benchmark crypto_pyaes failed: Benchmark died
Traceback (most recent call last):
  File "/home/kmod/python-benchmarks/tester/data/build/pyston/build/system_env/lib/python3.8/site-packages/pyperformance/run.py", line 131, in run_benchmarks
    result = bench.run(
  File "/home/kmod/python-benchmarks/tester/data/build/pyston/build/system_env/lib/python3.8/site-packages/pyperformance/_benchmark.py", line 185, in run
    bench = _run_perf_script(
  File "/home/kmod/python-benchmarks/tester/data/build/pyston/build/system_env/lib/python3.8/site-packages/pyperformance/_benchmark.py", line 221, in _run_perf_script
    _utils.run_command(argv, env=env, hide_stderr=not verbose)
  File "/home/kmod/python-benchmarks/tester/data/build/pyston/build/system_env/lib/python3.8/site-packages/pyperformance/_utils.py", line 116, in run_command
    raise RuntimeError("Benchmark died")
RuntimeError: Benchmark died
```

**Comment by gvanrossum** [comment]
Same as #107?

**Comment by kmod** [comment]
Ah, yeah looks like it
