### ISSUE TITLE
unpickle_pure_python broken on Python 3.8 beta1

### ISSUE THREAD

**Issue by vstinner** [python/pyperformance#59]
```
2019-06-06 08:14:37,403: [46/47] unpickle_pure_python...
2019-06-06 08:14:37,404: INFO:root:Running `/home/haypo/bench_tmpdir/venv/bin/python -u /home/haypo/pyperformance/pyperformance/benchmarks/bm_pickle.py --pure-python unpickle --verbose --output /tmp/tmp2jgtqf2c`
2019-06-06 08:14:37,471: Traceback (most recent call last):
2019-06-06 08:14:37,471:   File "/home/haypo/pyperformance/pyperformance/benchmarks/bm_pickle.py", line 287, in <module>
2019-06-06 08:14:37,471:     import pickle
2019-06-06 08:14:37,471:   File "/home/haypo/bench_tmpdir/prefix/lib/python3.9/pickle.py", line 39, in <module>
2019-06-06 08:14:37,471:     from _pickle import PickleBuffer
2019-06-06 08:14:37,471: ModuleNotFoundError: import of _pickle halted; None in sys.modules
2019-06-06 08:14:37,477: ERROR: Benchmark unpickle_pure_python failed: Benchmark died
```

Upstream issue closed as WONTFIX: https://bugs.python.org/issue37210

**Comment by vstinner** [comment]
I fixed Python 3.8: Python 3.8 beta2 will include my fix.
https://bugs.python.org/issue37210
