### ISSUE TITLE
Django and Tornado benchmarks broken on Python 3.9

### ISSUE THREAD

**Issue by vstinner** [python/pyperformance#76]
See also issue #74.

```
2019-12-17 01:04:41,423: [42/47] tornado_http...
2019-12-17 01:04:41,424: INFO:root:Running `/home/haypo/bench_tmpdir/venv/bin/python -u /home/haypo/pyperformance/pyperformance/benchmarks/bm_tornado_http.py --verbose --output /tmp/tmp8_0ujs9g`
2019-12-17 01:04:41,537: Traceback (most recent call last):
2019-12-17 01:04:41,537:   File "/home/haypo/pyperformance/pyperformance/benchmarks/bm_tornado_http.py", line 15, in <module>
2019-12-17 01:04:41,537:     from tornado.httpclient import AsyncHTTPClient
2019-12-17 01:04:41,537:   File "/home/haypo/bench_tmpdir/venv/lib/python3.9/site-packages/tornado/httpclient.py", line 50, in <module>
2019-12-17 01:04:41,537:     from tornado import gen, httputil, stack_context
2019-12-17 01:04:41,537:   File "/home/haypo/bench_tmpdir/venv/lib/python3.9/site-packages/tornado/httputil.py", line 107, in <module>
2019-12-17 01:04:41,537:     class HTTPHeaders(collections.MutableMapping):
2019-12-17 01:04:41,537: AttributeError: module 'collections' has no attribute 'MutableMapping'
```

and

```
2019-12-17 00:43:47,774: [ 6/47] django_template...
2019-12-17 00:43:47,775: INFO:root:Running `/home/haypo/bench_tmpdir/venv/bin/python -u /home/haypo/pyperformance/pyperformance/benchmarks/bm_django_template.py --verbose --output /tmp/tmp32v4efa1`
2019-12-17 00:43:47,925: Traceback (most recent call last):
2019-12-17 00:43:47,925:   File "/home/haypo/pyperformance/pyperformance/benchmarks/bm_django_template.py", line 38, in <module>
2019-12-17 00:43:47,925:     django.setup()
2019-12-17 00:43:47,925:   File "/home/haypo/bench_tmpdir/venv/lib/python3.9/site-packages/django/__init__.py", line 18, in setup
2019-12-17 00:43:47,925:     from django.urls import set_script_prefix
2019-12-17 00:43:47,925:   File "/home/haypo/bench_tmpdir/venv/lib/python3.9/site-packages/django/urls/__init__.py", line 1, in <module>
2019-12-17 00:43:47,926:     from .base import (
2019-12-17 00:43:47,926:   File "/home/haypo/bench_tmpdir/venv/lib/python3.9/site-packages/django/urls/base.py", line 11, in <module>
2019-12-17 00:43:47,926:     from .exceptions import NoReverseMatch, Resolver404
2019-12-17 00:43:47,926:   File "/home/haypo/bench_tmpdir/venv/lib/python3.9/site-packages/django/urls/exceptions.py", line 3, in <module>
2019-12-17 00:43:47,926:     from django.http import Http404
2019-12-17 00:43:47,926:   File "/home/haypo/bench_tmpdir/venv/lib/python3.9/site-packages/django/http/__init__.py", line 5, in <module>
2019-12-17 00:43:47,926:     from django.http.response import (
2019-12-17 00:43:47,926:   File "/home/haypo/bench_tmpdir/venv/lib/python3.9/site-packages/django/http/response.py", line 13, in <module>
2019-12-17 00:43:47,926:     from django.core.serializers.json import DjangoJSONEncoder
2019-12-17 00:43:47,926:   File "/home/haypo/bench_tmpdir/venv/lib/python3.9/site-packages/django/core/serializers/__init__.py", line 23, in <module>
2019-12-17 00:43:47,926:     from django.core.serializers.base import SerializerDoesNotExist
2019-12-17 00:43:47,927:   File "/home/haypo/bench_tmpdir/venv/lib/python3.9/site-packages/django/core/serializers/base.py", line 4, in <module>
2019-12-17 00:43:47,927:     from django.db import models
2019-12-17 00:43:47,927:   File "/home/haypo/bench_tmpdir/venv/lib/python3.9/site-packages/django/db/models/__init__.py", line 5, in <module>
2019-12-17 00:43:47,927:     from django.db.models.deletion import (
2019-12-17 00:43:47,927:   File "/home/haypo/bench_tmpdir/venv/lib/python3.9/site-packages/django/db/models/deletion.py", line 5, in <module>
2019-12-17 00:43:47,927:     from django.db.models import signals, sql
2019-12-17 00:43:47,927:   File "/home/haypo/bench_tmpdir/venv/lib/python3.9/site-packages/django/db/models/sql/__init__.py", line 2, in <module>
2019-12-17 00:43:47,927:     from django.db.models.sql.query import *  # NOQA
2019-12-17 00:43:47,927:   File "/home/haypo/bench_tmpdir/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 11, in <module>
2019-12-17 00:43:47,927:     from collections import Counter, Iterator, Mapping, OrderedDict
2019-12-17 00:43:47,927: ImportError: cannot import name 'Iterator' from 'collections' (/home/haypo/bench_tmpdir/prefix/lib/python3.9/collections/__init__.py)
2019-12-17 00:43:47,941: ERROR: Benchmark django_template failed: Benchmark died
```

**Comment by vstinner** [comment]
Fixed by:

* Django: commit 0872e29937ad526a7703c2359cdc5d53854b595b
* Tornado: commit 89656c4c248ce85612f7b9c7b3368d106689bcb4
